---
- hosts: server2.abc.com
  remote_user: Test1
  become: true
  gather_facts: true
  tasks: 
     - name: Install httpd package
       yum: name=httpd state=installed
     - name: copy index.html
       copy: src=index.html dest=/var/www/html/index.html
     - name: start httpd servcie
       service: name=httpd state=started 
       register: result
     - debug: var=result
