---
- hosts: server2.abc.com
  remote_user: Test1
  become: true
  gather_facts: true
  tasks: 
     - name: create tomcat directory
      # command: mkdir /usr/local/tomcat
       file: 
           path: /usr/local/tomcat
           state: directory
     - name: Download Tomcat
     #  command: wget http://apache.mirrors.nublue.co.uk/tomcat/tomcat-7/v7.0.100/bin/apache-tomcat-7.0.100.tar.gz
       get_url: 
             url: http://apache.mirrors.nublue.co.uk/tomcat/tomcat-7/v7.0.100/bin/apache-tomcat-7.0.100.tar.gz
             dest: /usr/local/tomcat
      - name: Extract tomcat
        unarchive:
               src: /opt/tomcat/apache-tomcat-7.0.100.tar.gz
               dest: /opt/tomcat
     - name: Create tomcat users
       copy: src=tomcat-users.xml dest=/opt/tomcat/apache-tomcat-7.0.100/conf
     - name: Deploy sample application
       copy: src=sample.war dest=/opt/tomcat/apache-tomcat-7.0.100/webapps
 
     - name: start tomcat
       shell: nohup  /opt/tomcat/apache-tomcat-7.0.100/bin/catalina.sh start
       register: result 
      
     - name: create directory
       command: mkdir /yyy
              
