---
# tasks file for webserver
- name: Install httpd package
  yum: name=httpd state=installed
- name: copy index.html
  copy: src=index.html dest=/var/wwww/html
  notify: restart httpd service
- name: start httpd service
  service: name=httpd state=started
